name: NoDeathOnTp
main: me.tabinol.nodeathontp.NoDeathOnTp
version: ${project.version}-b${build.number}
permissions:
    nodeathontp.notify:
        description: Notify for death cancellation
        default: op
